#parsed_test_dir: "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/test_attribute_extractor/data/parsed_test"
parsed_test_dir: "./data/output/parsed_tests"
results_dir: "./data/output/final"
logs_dir: "./data/output/logs"
#logs_dir: "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/test_attribute_extractor/data/results/logs"

tests:
  atm:
    dir: "./data/atm_tests"
    file_globs: []
      # - "*/*/*.java"
      # - "ground_truth/*/*.json"
  craftdroid:
    dir: "./data/craftdroid_tests"
    file_globs: 
      - "*/b*2/base/*.json"
      # - "a3/b31/base/*.json"
      # - "a4/b41/base/*.json"

