# model_dir: "/home/amohebbi/models/"
parsed_test_dir: "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/test_attribute_extractor/data/parsed_test"
#parsed_test_dir: "/home/faride/AppTestMigrator/appium_test/faride/test_attribute_extractor/data/parsed_test"
tests:
  atm:
    dir: "./data/atm_tests"
    file_globs: 
      - "*/*/*.java"
  craftdroid:
    dir: "./data/craftdroid_tests"
    file_globs:
      - "*/b*2/base/*.json"
      - "a3/b31/base/*.json"
      - "a4/b41/base/*.json"
