algorithm = "atm"
[atm]
    [atm.MIGRATION_CONFIGS]
    address = '../data/original_tests/atm/generated/*'
    erroneous_address = '../data/broken_tests/atm/'

    [atm.src_gt]
    address = "../data/mappings/atm/src_ground_truth/src_ground_truth.csv"

    [atm.gt_gen]
    address = "../data/mappings/atm/ground_truth_generated/"

    [atm.result]
    address = "../data/output/evaluation/atm/result_"
    aggregated_result_address = "../data/output/analyse/atm/atm_aggregated_result.csv"

    [atm.BASE_JSON_ADDRESS]
    address = '../data/json_tests/atm/'
    generated = '../data/json_tests/atm/generated/'

    [atm.BASE_LOG_ADDRESS]
    address = '../data/output/logs/atm/'
    generated = '../data/output/logs/atm/generated/'

    [atm.GROUND_TRUTH_GLOBE]
    address = '../data/json_tests/atm/ground_generatedtruth/*/*.json'






[craftdroid]
    [craftdroid.src_gt]
    address = "../data/evaluation/input/craftdroid/src_groundTruth.csv"

    [craftdroid.gt_gen]
    address = "../data/evaluation/input/craftdroid/groundTruth_generated_"

    [craftdroid.result]
    address = "../data/evaluation/output/craftdroid/result_"
    aggregated_result_address = "../data/evaluation/output/craftdroid/aggregated_result.csv"

    [craftdroid.BASE_JSON_ADDRESS]
    address = '../data/output/final/craftdroid_tests/'

    [craftdroid.BASE_LOG_ADDRESS]
    address = '../data/output/log/craftdroid_tests/'

    [craftdroid.GROUND_TRUTH_GLOBE]
    address = '../data/output/final/craftdroid_tests/*.json'

    [craftdroid.MIGRATION_CONFIGS]
    address = '../data/craftdroid_tests/generated/*'
    erroneous_address = '../data/evaluation/output/craftdroid/erroneous_generated'
