[data]
    [data.src_gt]
    address = "./input/src_groundTruth.csv"

    [data.gt_gen]
    address = "./input/groundTruth_generated.csv"

    [data.result]
    address = "./output/result.csv"

    [data.GROUND_TRUTH_GLOBE]
    address = '../data/output/final/atm_tests/ground_truth/*/*.json'

    [data.GENERATED_GLOBE]
    address = '../data/output/final/atm_tests/migrated_tests/*/*.json'

[sizes]
    [sizes.src]
    size = 4

    [sizes.gt]
    size = 5

    [sizes.gen]
    size = 6
