[data]
    [data.src_gt]
    address = "./input/src_groundTruth.csv"

    [data.gt_gen]
    address = "./input/groundTruth_generated_"

    [data.result]
    address = "./output/result_"

    [data.BASE_JSON_ADDRESS]
    address = '../data/output/final/atm_tests/'

    [data.GROUND_TRUTH_GLOBE]
    address = '../data/output/final/atm_tests/ground_truth/*/*.json'

    [data.MIGRATION_CONFIGS]
    address = '../../generated/*'
