algorithm = "atm"
[atm]
    [atm.MIGRATION_CONFIGS]
    address = '../data/original_tests/atm/generated/*'
    erroneous_address = '../data/broken_tests/atm/'

    [atm.src_gt]
    address = "../data/mappings/atm/src_ground_truth/src_ground_truth.csv"

    [atm.gt_gen]
    address = "../data/mappings/atm/ground_truth_generated/"

    [atm.result]
    address = "../data/output/evaluation/atm/result_"
    aggregated_result_address = "../data/output/analyse/atm/atm_aggregated_result.csv"

    [atm.BASE_JSON_ADDRESS]
    address = '../data/json_tests/atm/'
    generated = '../data/json_tests/atm/generated/'

    [atm.BASE_LOG_ADDRESS]
    address = '../data/output/logs/atm/'
    generated = '../data/output/logs/atm/generated/'

    [atm.GROUND_TRUTH_GLOBE]
    address = '../data/json_tests/atm/ground_truth/*/*.json'






[craftdroid]
    [craftdroid.MIGRATION_CONFIGS]
    address = '../data/original_tests/craftdroid/generated/*'
    erroneous_address = '../data/broken_tests/craftdoid/'

    [craftdroid.src_gt]
    address = "../data/mappings/craftdroid/src_ground_truth/src_ground_truth.csv"

    [craftdroid.gt_gen]
    address = "../data/mappings/craftdroid/ground_truth_generated/"

    [craftdroid.result]
    address = "../data/output/evaluation/craftdroid/result_"
    aggregated_result_address = "../data/output/analyse/craftdroid/craftdroid_aggregated_result.csv"

    [craftdroid.BASE_JSON_ADDRESS]
    address = '../data/json_tests/craftdroid/'
    generated = '../data/json_tests/craftdroid/generated/'

    [craftdroid.BASE_LOG_ADDRESS]
    address = '../data/output/logs/craftdroid/'
    generated = '../data/output/logs/craftdroid/generated/'

    [craftdroid.GROUND_TRUTH_GLOBE]
    address = '../data/json_tests/craftdroid/ground_truth/*.json'

    
