algorithm = "atm"
[atm]
    [atm.src_gt]
    address = "../data/evaluation/input/atm/src_groundTruth.csv"

    [atm.gt_gen]
    address = "../data/evaluation/input/atm/groundTruth_generated_"

    [atm.result]
    address = "../data/evaluation/output/atm/result_"
    aggregated_result_address = "../data/evaluation/output/atm/aggregated_result.csv"

    [atm.BASE_JSON_ADDRESS]
    address = '../data/output/final/atm_tests/'

    [atm.BASE_LOG_ADDRESS]
    address = '../data/output/logs/atm_tests/'

    [atm.GROUND_TRUTH_GLOBE]
    address = '../data/output/final/atm_tests/ground_truth/*/*.json'

    [atm.MIGRATION_CONFIGS]
    address = '../data/atm_tests/generated/*'
    erroneous_address = '../data/evaluation/output/atm/erroneous_generated'
[craftdroid]
    [craftdroid.src_gt]
    address = "../data/evaluation/input/craftdroid/src_groundTruth.csv"

    [craftdroid.gt_gen]
    address = "../data/evaluation/input/craftdroid/groundTruth_generated_"

    [craftdroid.result]
    address = "../data/evaluation/output/craftdroid/result_"
    aggregated_result_address = "../data/evaluation/output/craftdroid/aggregated_result.csv"

    [craftdroid.BASE_JSON_ADDRESS]
    address = '../data/output/final/craftdroid_tests/'

    [craftdroid.BASE_LOG_ADDRESS]
    address = '../data/output/log/craftdroid_tests/'

    [craftdroid.GROUND_TRUTH_GLOBE]
    address = '../data/output/final/craftdroid_tests/*.json'

    [craftdroid.MIGRATION_CONFIGS]
    address = '../data/craftdroid_tests/generated/*'
    erroneous_address = '../data/evaluation/output/craftdroid/erroneous_generated'
